# Generated by Django 3.2.16 on 2023-02-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='follower',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='participant',
            new_name='participants',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='cause',
            name='tags',
            field=models.ManyToManyField(related_name='cause_tags', to='makethedifference.Tag'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='makethedifference.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(related_name='event_tags', to='makethedifference.Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
