# Generated by Django 3.2.16 on 2023-02-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0003_rename_creator_user_creator_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='image',
            field=models.ImageField(default='thelogo.PNG', upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='thelogo.PNG', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
    ]
