# Generated by Django 3.2.16 on 2023-02-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0006_auto_20230204_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
