# Generated by Django 3.2.16 on 2023-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0009_auto_20230206_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='likes',
            field=models.ManyToManyField(related_name='cause_likes', to='makethedifference.User'),
        ),
    ]
