# Generated by Django 3.2.16 on 2023-02-09 15:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0010_cause_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='event_likes', to='makethedifference.User'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='thelogo.PNG', force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, 250], upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='thelogo.PNG', force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, 250], upload_to=''),
        ),
    ]
