# Generated by Django 3.2.16 on 2023-02-10 12:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0011_auto_20230209_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='thelogo.PNG', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to=''),
        ),
    ]
