# Generated by Django 3.2.16 on 2023-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0012_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
