# Generated by Django 3.2.16 on 2023-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makethedifference', '0015_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
